/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import clases.Producto;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author salon
 */
public class VistaGestionProductos extends javax.swing.JFrame {
         private ArrayList<Producto>listaProducto=new ArrayList();
         private DefaultTableModel modeloTabla = new DefaultTableModel(){
             
                 @Override
                 public boolean isCellEditable(int fila, int columna) {
                     return false;
                 }
         };
    /**
     * Creates new form VistaGestionProductos
     */
    public VistaGestionProductos() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.BLACK);
        comboCategoria();
        modelarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPanelGeneral = new javax.swing.JPanel();
        jpPanelCarga = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jtPrecio = new javax.swing.JTextField();
        jcCategoria = new javax.swing.JComboBox<>();
        jbAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaProductos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jbLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpPanelGeneral.setBackground(new java.awt.Color(51, 51, 51));

        jpPanelCarga.setBackground(new java.awt.Color(51, 51, 51));
        jpPanelCarga.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Categoria:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precio($):");

        jtNombre.setBackground(new java.awt.Color(102, 102, 102));
        jtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtNombre.setForeground(new java.awt.Color(0, 204, 204));

        jtPrecio.setBackground(new java.awt.Color(102, 102, 102));
        jtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtPrecio.setForeground(new java.awt.Color(0, 204, 204));

        jcCategoria.setBackground(new java.awt.Color(102, 102, 102));
        jcCategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcCategoria.setForeground(new java.awt.Color(0, 204, 204));

        jbAgregar.setBackground(new java.awt.Color(0, 0, 0));
        jbAgregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jbAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-add-shopping-cart-32.png"))); // NOI18N
        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPanelCargaLayout = new javax.swing.GroupLayout(jpPanelCarga);
        jpPanelCarga.setLayout(jpPanelCargaLayout);
        jpPanelCargaLayout.setHorizontalGroup(
            jpPanelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelCargaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jpPanelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGroup(jpPanelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanelCargaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jpPanelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtNombre)
                            .addComponent(jcCategoria, 0, 201, Short.MAX_VALUE)
                            .addComponent(jtPrecio)))
                    .addGroup(jpPanelCargaLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jbAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPanelCargaLayout.setVerticalGroup(
            jpPanelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelCargaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jpPanelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jpPanelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPanelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jtaProductos.setBackground(new java.awt.Color(51, 51, 51));
        jtaProductos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtaProductos.setForeground(new java.awt.Color(0, 204, 0));
        jtaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtaProductos);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-hierarchy-96 (1).png"))); // NOI18N
        jLabel4.setText("Gestion de Productos");

        jbLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        jbLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jbLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-clean-32.png"))); // NOI18N
        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPanelGeneralLayout = new javax.swing.GroupLayout(jpPanelGeneral);
        jpPanelGeneral.setLayout(jpPanelGeneralLayout);
        jpPanelGeneralLayout.setHorizontalGroup(
            jpPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelGeneralLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jpPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jpPanelCarga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jbLimpiar))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jpPanelGeneralLayout.setVerticalGroup(
            jpPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelGeneralLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpPanelCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbLimpiar)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        // TODO add your handling code here:
        try{
            int precio=Integer.parseInt(jtPrecio.getText());
            String nombre=jtNombre.getText();
            String categoria=(String) jcCategoria.getSelectedItem();
            if(!nombre.isEmpty()){
            Producto p = new Producto(nombre,categoria,precio);
            listaProducto.add(p);
            datosTabla(listaProducto);
            JOptionPane.showMessageDialog(this, "¡Producto agregado a la tabla!", "Producto guardado", JOptionPane.INFORMATION_MESSAGE);
            jtPrecio.setText("");
            jtNombre.setText("");
            }else{
             JOptionPane.showMessageDialog(this, "Los campos de texto estan vacios", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Precio solo acepta valores numericos", "Error en el precio", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        modeloTabla.getDataVector().removeAllElements();
        modeloTabla.fireTableDataChanged();
    }//GEN-LAST:event_jbLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGestionProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGestionProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGestionProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGestionProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaGestionProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JComboBox<String> jcCategoria;
    private javax.swing.JPanel jpPanelCarga;
    private javax.swing.JPanel jpPanelGeneral;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTable jtaProductos;
    // End of variables declaration//GEN-END:variables
    public void comboCategoria(){
        jcCategoria.addItem("Perfumeria");
        jcCategoria.addItem("Comestible");
        jcCategoria.addItem("Limpieza");
        jcCategoria.addItem("Farmacia");
        jcCategoria.addItem("Ropa");
    }
    public void modelarTabla(){
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Categoria");
        modeloTabla.addColumn("Precio");
        jtaProductos.setModel(modeloTabla);
    }
    public void datosTabla(ArrayList<Producto> producto){
        modeloTabla.getDataVector().removeAllElements();
        for(Producto i:producto){
            modeloTabla.addRow(new Object[]{i.getNombre(),i.getCategoria(), "$"+i.getPrecio()});
        }
    }

}
